version: '3.7'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: r2ls
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./var/db-data:/var/lib/postgresql/data:rw
  php-fpm:
    build: ./docker/php-fpm-dev
    volumes:
    - ./:/app
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  nginx:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
    - ./:/app
    - ./var/log/nginx:/var/log/nginx
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    working_dir: /app
